name: Package

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'

jobs:
  pyinstaller:
    runs-on: windows-latest
    steps:
      - name: Setup Time Zone
        run: tzutil /s "China Standard Time"
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: Build with PyInstaller
        shell: cmd
        run: .\build.bat -y
      - name: Upload file
        uses: actions/upload-artifact@v4
        with:
          name: douyin-rtmp-pyinstaller
          path: ${{ github.workspace }}/dist/douyin-rtmp.exe

  nuitka:
    runs-on: windows-latest
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: Setup Time Zone
        run: tzutil /s "China Standard Time"
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: Build with Nuitka
        shell: cmd
        run: .\build.bat -y nuitka
      - name: Upload file
        uses: actions/upload-artifact@v4
        with:
          name: douyin-rtmp-nuitka
          path: ${{ github.workspace }}/nuitka_out/douyin-rtmp-nuitka.exe
